package codekonami;

/**
 *
 * Interfaz gráfica de Acerca de
 *
 * @author SrUsuario
 */
public class AboutDialog extends javax.swing.JDialog {

    /**
     * Creates new form AboutDialog
     *
     * @param parent owner the Frame from which the dialog is displayed
     * @param modal specifies whether dialog blocks user input to other
     * top-level
     */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlMain = new javax.swing.JPanel();
        jLblTItle = new javax.swing.JLabel();
        jLblVersion = new javax.swing.JLabel();
        jLblDescription = new javax.swing.JLabel();
        jLblAuthor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acerca de");

        jPnlMain.setLayout(new java.awt.GridLayout(4, 0));

        jLblTItle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLblTItle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblTItle.setText("Code Konami");
        jPnlMain.add(jLblTItle);

        jLblVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblVersion.setText("Versión 1.2 - 4 de octubre de 2023");
        jPnlMain.add(jLblVersion);

        jLblDescription.setText("Es un programa escrito en Java que prueba un código konami");
        jPnlMain.add(jLblDescription);

        jLblAuthor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblAuthor.setText("Autor: SrUsuario");
        jPnlMain.add(jLblAuthor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLblAuthor;
    private javax.swing.JLabel jLblDescription;
    private javax.swing.JLabel jLblTItle;
    private javax.swing.JLabel jLblVersion;
    private javax.swing.JPanel jPnlMain;
    // End of variables declaration//GEN-END:variables
}
